openapi: 3.0.1
info:
  title: yGptPlugin
  version: 1.0.0
paths:
  '/api/ai/sql':
    get:
      summary: Use natural language to query a database containing data on Yearn vaults and strategies
      operationId: sql
      parameters:
        - in: query
          name: languageQuery
          schema:
            type: string
          description: A natural language query. 
      responses:
        '200':
          description: Vault and strategy data
          content:
            application/json:
              schema:
                type: object
                properties:
                  vaults:
                    type: array
                    description: Array of Yearn vaults and their strategies
                    items:
                      type: object
                      description: A Yearn vault
                      properties:
                        address:
                          type: string
                        version:
                          type: string
                        token_symbol:
                          type: string
                        name:
                          type: string
                        net_annual_percent_yield:
                          type: number
                        gross_annual_percent_yield:
                          type: number
                        url:
                          type: string
                        strategies:
                          type: array
                          description: Array of strategies used by a Yearn vault
                          properties:
                            address:
                              type: string
                            name:
                              type: string
                            description:
                              type: string
                            total_debt_usd:
                              type: number
                            net_annual_percent_rate:
                              type: number
                            last_report:
                              type: date
